### PR TITLE
remove docker run interactive flag

### PR DESCRIPTION
**Pull request by zhajianl**
remove docker run interactive flag in order to let user do automation testing on host

### CODE REVIEW

**Comment by dvintel** [comment]
@brod-intel Is the interactive shell needed for "regular" use case?

**Review by sunausti — APPROVED** [review]

**Review by Krishnendhu-Prakasan — COMMENTED** [review]
LGTM.

**Review by brod-intel — CHANGES_REQUESTED** [review]
We MUST have interactive (-i) for vpxe.sh, otherwise we will not be able to interact with vpxe should the process fail.  The system will be in a stalled state.

**Comment by zhajianl** [comment]
> interact

got it, thanks, we can abort this patch.

**Pull request closed without merging**
